### ISSUE TITLE
Where to find sample_config.yaml

### ISSUE THREAD

**Issue by rz001** [bcbio/bcbio-nextgen-vm#170]
Hello,

I just installed bcbio_vm.py and I would like to run it with test data, however I cannot find sample_config.yaml file.  

Thanks for info.
R.

**Comment by chapmanb** [comment]
The sample configuration file is a customized input file describing your samples and analysis. There are more details about building and creating it in the documentation:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html

Does this provide a useful starting point for getting your test data analysis going? Hope this is helpful.

**Comment by chapmanb** [comment]
Glad that helps and please let us know if you have specific questions. Once you reach sample specification things do get less automated as you have lot of different choices depending on your samples and the type of analysis you're looking to run. We've tried to automate as much as possible of that and please let us know if we can help at all to make it easier to get started.
