### ISSUE TITLE
Toil, cwl, bcbio - ImportError: cannot import name 'fillInDefaults' from 'cwltool.process'

### ISSUE THREAD

**Issue by dennis-kao** [bcbio/bcbio-nextgen-vm#175]
Hi bcbio team!

Thanks for making such an amazing pipeline.

I installed bcbio-vm with a local installation of bcbio as indicated here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#running-with-toil-local-hpc

I set bcbio_vm.py to be apart of my path. I ran run_toil.sh from here: https://github.com/bcbio/test_bcbio_cwl/archive/master.tar.gz
t

and got this error: 

> [dennis.kao@qlogin12 somatic]$ ./run_toil.sh
> Running: export PATH="$PATH":/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/bin && cwltoil --jobStore /hpf/largeprojects/ccmbio/dennis.kao/test_bcbio_cwl-master/somatic/toil_work/cwltoil_jobstore --logFile /hpf/largeprojects/ccmbio/dennis.kao/test_bcbio_cwl-master/somatic/toil_work/somatic-toil.log --workDir /hpf/largeprojects/ccmbio/dennis.kao/test_bcbio_cwl-master/somatic/toil_work/tmpdir --linkImports --restart --no-container --preserve-environment PATH HOME -- /hpf/largeprojects/ccmbio/dennis.kao/test_bcbio_cwl-master/somatic/somatic-workflow/main-somatic.cwl /hpf/largeprojects/ccmbio/dennis.kao/test_bcbio_cwl-master/somatic/somatic-workflow/main-somatic-samples.json
> 'draft2tool.py' has been renamed to 'command_line_tool.py'and will be removed in the future.
> Traceback (most recent call last):
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/bin/cwltoil", line 6, in <module>
>     from toil.cwl.cwltoil import main
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 42, in <module>
>     from cwltool.process import shortname, fillInDefaults, compute_checksums, collectFilesAndDirs, stageFiles
> ImportError: cannot import name 'fillInDefaults' from 'cwltool.process' (/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/site-packages/cwltool/process.py)
> Traceback (most recent call last):
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/bin/bcbio_vm.py", line 354, in <module>
>     args.func(args)
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/site-packages/bcbio/cwl/tool.py", line 369, in run
>     _TOOLS[args.tool](args)
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/site-packages/bcbio/cwl/tool.py", line 131, in _run_toil
>     _run_tool(cmd, not args.no_container, work_dir)
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/site-packages/bcbio/cwl/tool.py", line 47, in _run_tool
>     subprocess.check_call(cmd, shell=True)
>   File "/hpf/largeprojects/ccmbio/dennis.kao/bcbio/anaconda/envs/bcbiovm/lib/python3.7/subprocess.py", line 347, in check_call
>     raise CalledProcessError(retcode, cmd)
> 

I've tried to revert the cwltool library back to a version which has fillInDefaults in the past and I remember getting stuck somewhere regarding toil only being able to run on Python 2.

Why are the dependencies out of sync for running a workflow that uses CWL and Toil?

**Comment by chapmanb** [comment]
Dennis;
Sorry about the issues with Toil. Currently we're still working to get a Toil version with the same CWL dependency requirements as other CWL tools like Arvados so this will work correctly and we can ship toil along with bcbio-vm. https://github.com/bcbio/bcbio-nextgen/issues/2799 has the ongoing discussion, where we need a new Toil release to get us in sync and https://github.com/bcbio/bcbio-nextgen/issues/2710 is a longer earlier discussion.

Apologies about not having this synced right now for CWL Toil support. If using Cromwell is an option that should work cleanly for CWL runs and we'll work to get Toil updated on the next release. Thanks much for trying this all out and hope this helps.

**Comment by dennis-kao** [comment]
Hi Brad,
Thanks for letting me know about Cromwell! It's a good alternative to Toil.
